### ISSUE TITLE
RFC: Security Issue Reporting Proposal

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/sig-security#12]
### Summary:
Define a security reporting process for O3DE security issues that *makes it obvious*.

Note: This was originally started as a [discussion](https://github.com/o3de/sig-security/discussions/9). There will also be a second RFC to cover response procedure to reported issues.

### What is the relevance of this feature?
O3DE needs to have a secure vulnerability reporting process for security related issues such that:

* External security processes can report issues - such as automated software scanning, security researchers etc. 
* External security reporters can report securely - they can report issues to O3DE in a way that does not disclose any confidential information or identities.
* Malicious or false alarms are filtered to prevent causing concern or confusion to the O3DE community.
* The process provides a buffer to allow mitigation of critical issues, prior to public disclosure.

See https://docs.github.com/en/code-security/security-advisories/about-coordinated-disclosure-of-security-vulnerabilities for guidance around open source projects and https://github.com/ossf/oss-vulnerability-guide/blob/main/guide.md#response-process.

### Feature design description:
Security reporting for O3DE should make things obvious and provide clear, consistent documentation so this RFC proposes four main changes:

* Adding a monitored email list to report issues
* Adding a *Security* section on the o3de.org website that is easily discoverable
* Adding a GitHub issue template, which directs reporters to use the security reporting process rather than GitHub issues.
* Adding a SECURITY.md file to the repro which covers security reporting, link to it from the README.md

#### Proposal #1: Setup monitored email list for reporting security vulnerabilities

Set-up an O3DE owned monitored email list for reporting security vulnerabilities such as [security@o3de.org](mailto:security@o3de.org). Need to ensure email attachments can be audited for spam and malware and that all access to the issues is performed with TLS in place.

Membership of the list needs to be strictly controlled so only SIG-security response team (definition and process TBD) and approved observers (nominated by TSC for example) see initial reports. The membership of this list and processes will be covered in a subsequent proposal.

The list ideally should offer encryption mechanisms for issue reporting. For example, SIG security offers public keys that reporters can use to encrypt secure content (public keys should be kept in the SIG-security repro).

#### Proposal #2: Add a Security Reporting Section to [o3de.org](http://o3de.org/) 

*Proposal: Add a security reporting section on [o3de.org](http://o3de.org/) and also in mark down in README.md in the [sig-security](https://github.com/o3de/sig-security) repro. Propose that SIG-security defines a release disclosure period similar to Kubernetes but with an initial longer disclosure default period while security reporting processes are built out.

Below is an approximate rough draft. Note: If reporting supports encryption, then should include instructions for signing/encrypting report. SIG-Security will work with SIG-docs-community to define location and language.

> All security vulnerabilities should be reported through via [security@o3de.org](mailto:security@o3de.org). Vulnerability reports should follow the same information reporting format as standard O3DE issues [o3de/o3de](https://github.com/o3de/o3de/blob/development/.github/ISSUE_TEMPLATE/bug_template.md).
>
> When to Report?
> 
> * You have discovered a potential security issue relating to O3DE.
> * You have discovered or are aware of a security issue relating to an O3DE dependency that may impact O3DE.
>
> When to not Report?
>
> * You need help setting up issues related to security dependencies such as OpenSSL or TLS/DTLS
> * You need help applying a security related fix to your O3DE applications.
> * Issue is not related to security. Please report issue using the normal O3DE issue reporting process.

##### Release Disclosure Period

The public disclosure date of the vulnerability will be negotiated between SIG-Security and the vulnerability reporter. The SIG aims to publicly disclose the issue as soon as mitigation as been identified and a patch is ready. SIG-Security aims to provide disclosure for within **14** days as long as the issue is well understood. If an issue is more complex and requires more time for reproduction and analysis, SIG-Security may delay disclosure.

#### Proposal #3: Separate Vulnerabilities from Bug Issues for O3DE Issue Reporting

Proposal: Modify issue reporting in O3DE repros to encourage folks to report security vulnerabilities correctly when they click “Create Issue”. This would create a new template in the repro, that links to the security reporting section of the O3DE website to discourage reporting via GitHub Issues (GHI).

_An example from another github repro (need to add link to source), SIG will work with relevant SIG to define language, but clicking the `view policy` will direct users to the security section on o3de.org.
![image(2)](https://user-images.githubusercontent.com/61438964/147991716-06734c06-5890-4ccd-9913-cfc1fa60ca09.png)

#### Proposal #4: Provide a SECURITY.md in o3de/o3de repro

Provide SECURITY.md in the main repro as per https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository#about-security-policies. Naming the file SECURITY.md will also fill out the "Security Policy" and "Security Advisory" information for the top-level security tab in the GitHub repro. See. https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

* Kubernetes example: https://github.com/kubernetes/kubernetes/blob/master/SECURITY_CONTACTS

Once we have an agreed SECURITY.md file, SIG-Security will then copy / asks SIGs to add copies to relevant other O3DE repositories.

### What are the advantages of the feature?
Follows Linux Foundation hosted projects suggest for open source project reporting and gives a secure and private mechanism for the intake of security issues for O3DE.

### What are the disadvantages of the feature?
Easy for reporters to submit incomplete or partial data which could delay reporting of critical issues. Relies on monitoring of external email list which could lead to delays in intake process.

Will need to define subsequent process to encrypt and decrypt information in another RFC.

### How will this be implemented or integrated into the O3DE environment?
n/a Feature will not be implemented in code or directed connected to O3DE

### Are there any alternatives to this feature?
SIG could provide hosted webform for issue intake but that adds complexity and prevents automated tooling from reporting issues (software scanners).

SIG could use [HackerOne](https://www.hackerone.com/company/open-source-community) which is used by some open source projects like [NodeJS](https://github.com/nodejs/node/blob/HEAD/SECURITY.md#security). However, the requirement for a one-week response time may be beyond this SIG while we are ramping up. Once SIG-Security has a mature process that's working SIG can revisit HackerOne.
### How will users learn this feature?
Uses will learn of this feature through the various publication mechanisms suggested:

* A SECURITY.md in the repro that directs people to this SIG and the reporting guidelines 
* A security section on the docs.o3de.org website
* A `report a security issue` feature in the GitHub issue templates that directs users to the docs.o3de.org website.

### Are there any open questions?
Proposal is that email list is security@o3de.org, following Linux Foundation suggestions for security@DOMAIN, could also use security-issues, security-reports etc.

### References

Two Linux Foundation hosted projects:
* [Kubernetes](https://kubernetes.io/docs/reference/issues-security/security/)
* [Edge X Foundry Security Process](https://wiki.edgexfoundry.org/display/FA/Security)

**Comment by dshmz** [comment]
Reviewed this RFC in our SIG meeting, we are good to go with it.

**Comment by amzn-changml** [comment]
No issues with the RFC

**Comment by myfoostrong** [comment]
Had submitted my comments to the draft of this RFC, and after the SIG has deliberated on this a few times I think this is good to go

**Comment by allisaurus** [comment]
+1 to accepting this RFC.

**Comment by lmbr-pip** [comment]
Will be archived by https://github.com/o3de/sig-security/pull/20
