### ISSUE TITLE
RFC for Security charter

### ISSUE THREAD

**Issue by dshmz** [o3de/sig-security#2]
Please provide feedback on the security charter

# SIG Security Charter

## Overview of SIG
SIG Security is a special interest group for O3DE code security that works as a central knowledge advisory group and  provides resources, consultation, reporting mechanisms  and information for security compliance, and security related issue resolution. This SIG also helps in keeping security patching up to date, and provide the basic services related to  APPSEC (Application Security) of O3DE.

## Goals

- To be set after rest of the charter is reviewed.

## Scope
-  Involves gathering information about security flaws. 
-  Identify potential security risks/gaps in Software.
-  Define best practices for ensuring secure code.

## In scope

- Triage and Acceptance of incoming security issues.
- Creating mechanisms for intake of private security issues from any source.
- Management of GitHub security advisories for the O3DE repros.
- Management of security reporting email and initial disclosure lists.
- Provides mechanisms for reporting security issues manually
- Provides tooling and automation for security issue identification and running campaigns to resolve identified security issues, including deprecation of software components.
- Provide SPDX (Software Package Data Exchange) scanning tools to detect violations.

## Cross-cutting Processes

- Disseminating information to other sigs for action / update/ fixing
- Review and provide feedback on SIG presented features and implementation
- Provide SPDX Licensing report violations to corresponding SIGs
- Advise SIGs on security level of new libraries 
- Provide web and docs team with links to campaign information stored in SIG's repository
- Provide consultation for compliance automation scanning at periodic intervals and point release intervals for each potential issue and report violations to appropriate SIGs.
- Advise Technical steering committee and Governing board of potential threats and unresolved issues.
- Items that span or require other SIGs or groups and how it relates to this SIG’s responsibilities

## Out of Scope
- Not responsible for fixing any detected or reported security issues.
- Not responsible for enforcing or acting upon any legal compliance issues.
- Not responsible for implementing security or IP detection tools into automation or build chains, but may advise SIGs on where to implement.
- Items that are optional or are not the responsibility of this SIG.

**SIG Links and lists:**

- Joining this SIG - https://github.com/orgs/o3de/teams/sig-security
- Slack/Discord - https://discord.com/channels/805939474655346758/816043899477950475 
- Mailing list - https://lists.o3de.org/g/sig-security
- Issues/PRs - https://github.com/o3de/sig-security/issues/
- Meeting agenda & Notes - https://github.com/o3de/sig-security/issues/1 

**Roles and Organization Management**

SIG Security adheres to the standards for roles and organization management as specified by <sig-governance>. This SIG opts in to updates and modifications to <sig-governance>

**Individual Contributors**

Additional information not found in the sig-governance related to contributors.

**Maintainers**

Additional information not found in the sig-governance related to contributors

**Additional responsibilities of Chairs**

Additional information not found in the sig-governance related to SIG Chairs

**Subproject Creation**

Additional information not found in the sig-governance related to subproject creation

**Deviations from sig-governance**

Explicit Deviations from the sig-governance

**Comment by lmbr-pip** [comment]
Thoughts:

## Overview of SIG
- Needs new draft as IMHO it does not capture what SIG-Security is in a readable way.
- IMHO "security of systems and infrastructure" is vague and misses that majority of our work is code security.
- "Provides the basic services of APPSEC" - should be clear that we mean Application Security here and what this really means
- Should cover we own reporting mechanisms (both manual and automatic)


## Goals
- We should have some goals defined (However, this can come after general charter cleanup).

## In Scope
* SIG should own management of GitHub security advisories for the O3DE repros.
* SIG owns and manages security reporting email and initial disclosure lists
* SIG owns triage and acceptance of incoming security issues.
* "Create tooling and campaigns to identify and resolve gaps, holes and the deprecation of software" - seems to muddy a number of things together, would split into:  mechanisms for reporting security issues manually, tooling for automating security issue identification and running campaigns to resolve identified security issues, including deprecation of software components
* "Provide security audit for each SIG during an open campaign" - the word audit is very unclear here in terms of what services we are providing SIGs
* SPDX scanning - can we link to SPDX information so its clear what this is, I would also combine or place adjacent to automation tooling for security issues.
* "Provide and report on penetration testing" - we do not have the capacity to provide penetration testing IMHO, we can certainly advise on it
*

## Cross-cutting
* "to published compliance list" - its unclear what the compliance list is
* "Team must provide compliance automation at periodic intervals" - Unsure if we have capacity for this, this should be "SIG aids in providing compliance automation" maybe?

## Out of scope
* "Not responsible for enforcing & acting upon any legal compliance issues" - I would guess we would triage these, I assume these would go to the TSC? Is that the intent of this wording that legal issues are not in our remit?

**Comment by dshmz** [comment]
I have implemented the review comments and updated the charter that we can review in our next SIG meeting.

**Comment by dshmz** [comment]
Closing this RFC after the implementation of review comments and review during the SIG meeting.
