### ISSUE TITLE
SIG Reviewer/Maintainer Nomination: allisaurus

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/sig-security#31]
### Maintainer Nomination

I would like to nominate: ***[allisaurus](https://github.com/allisaurus)***, to become a ***Maintainer*** on behalf of ***sig-Security***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***[allisaurus](https://github.com/allisaurus)***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

Note: This issue is skipping reviewer state as nominated person already holds reviewer/maintainer state in other SIGs, is an active member of SIG-Security and SIG-Security has need for extra maintainers to relieve burden on SIG Chair(s)

**Comment by allisaurus** [comment]
I accept this nomination and am glad to work as a maintainer for SIG-Security.

**Comment by lmbr-pip** [comment]
Discussed in SIG-Security meeting 4/27. Maintainer accepted by SIG.
