### ISSUE TITLE
SIG Reviewer/Maintainer Nomination: amzn-changml

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/sig-security#32]
### Maintainer Nomination

I would like to nominate: ***[amzn-changml](https://github.com/amzn-changml)***, to become a ***Maintainer*** on behalf of ***sig-Security***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***[amzn-changml](https://github.com/amzn-changml)***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

Note: This issue is skipping reviewer state as nominated person already holds reviewer/maintainer/admin state in other SIGs, is an active member of SIG-Security and SIG-Security has need for extra maintainers to relieve burden on SIG Chair(s)

**Comment by amzn-changml** [comment]
I, Mike Chang accept the nomination for maintainer position in the Security SIG. I understand the responsibilities and requirements of the role, and promise to faithfully fulfill them and follow all contributor requirements for O3DE.

Github User: amzn-changml
Discord User: MikeC [Amazon]#8546

**Comment by lmbr-pip** [comment]
Maintainer accepted by SIG in 4./27 meeting. SIG-Chair(s) to promote user to SIG maintainer.
