### ISSUE TITLE
Update SIG/security README with more details so its clear to new users what SIG does

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/sig-security#50]
Cover in more details What the SIG does? How do folks get involved? 

See SIG/Network for an example, https://github.com/o3de/sig-network

We should also link to our security reporting and response documentation (currently just in RFC form) and the o3de.org security docs: https://www.o3de.org/docs/contributing/security/

**Comment by dshmz** [comment]
Created and Reviewed in the SIG meeting - https://github.com/o3de/sig-security/blob/main/README.md
