### ISSUE TITLE
Create Roadmap View

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-security#64]
Hi! SIG release is working to help the O3DE community to get visibility of the O3DE roadmap. Full context can be read here: https://github.com/o3de/sig-release/issues/79. 

In order to achieve that goal, we need your help to create the roadmap for your SIG by **February 6th, 2023**, and start giving brief updates about the roadmap items at the **Joint TSC meeting on February 28th, 2023**. Instruction to create the roadmap view can be read in the RFC section "Roadmap Review in TSC monthly meeting".

Let me know if you have any concerns with the dates or any questions about the ask!

**Comment by vincent6767** [comment]
Hi @dshmz @lmbr-pip   , a friendly reminder to help review by next week as we want every SIG to have a roadmap according to the RFC attached above by February 6th, 2023.

**Comment by vincent6767** [comment]
Hi @dshmz @lmbr-pip , are there any updates about the security roadmap?

**Comment by lmbr-pip** [comment]
Roadmap is here https://github.com/orgs/o3de/projects/45 but do not have power to make it public.

**Comment by lmbr-pip** [comment]
Note: SIG/Security has no planned contributions for O3DE at this time. But will start reviewing at next SIG meeting

**Comment by vincent6767** [comment]
So that means SIG security will have roadmap soon?

**Comment by vincent6767** [comment]
In that case, I'll close the issue. Please add the label "kind/roadmap" on the roadmap item once you have the roadmap item. Thanks! @lmbr-pip
